### ISSUE TITLE
liyinnn~~~

### ISSUE THREAD

**Issue by ClueeZhuo** [cubesky/skyedge-blog#1]
May you share your blog theme?

**Comment by cubesky** [comment]
My blog theme using https://github.com/bolnh/hexo-theme-material , but this theme doesn;t update for a long time.  And it contains bug in newer hexo generator.

**Comment by ClueeZhuo** [comment]
Yes, I also use this theme, which encountered some problems, such as abnormal paging, and then I came to your example recommended by the official. I think it's convenient to quote your revised theme O (∩_∩) O？

**Comment by cubesky** [comment]
My blog is rendered by a CI script. And my hexo is pined to an old version in CI script. I have no change to offical theme repo. Just auto clone it and copy _config.yml to theme folder and build.

**Comment by ClueeZhuo** [comment]
666 ，Ok thanks for your reply ...
